# Generated by Django 4.2.1 on 2023-10-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_cajero_user_medico_user_paciente_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajero',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='user',
        ),
    ]
